// Auto-generated exercise catalog for /api/parse (id, name, category).
module.exports = [
  {"id":"CHEST_001","name":"Flat Barbell Bench Press","category":"Chest"},
  {"id":"CHEST_002","name":"Incline Barbell Bench Press","category":"Chest"},
  {"id":"CHEST_003","name":"Decline Barbell Bench Press","category":"Chest"},
  {"id":"CHEST_004","name":"Flat Dumbbell Bench Press","category":"Chest"},
  {"id":"CHEST_005","name":"Incline Dumbbell Press","category":"Chest"},
  {"id":"CHEST_006","name":"Decline Dumbbell Press","category":"Chest"},
  {"id":"CHEST_007","name":"Flat Dumbbell Fly","category":"Chest"},
  {"id":"CHEST_008","name":"Incline Dumbbell Fly","category":"Chest"},
  {"id":"CHEST_009","name":"Cable Crossover (High to Low)","category":"Chest"},
  {"id":"CHEST_010","name":"Cable Crossover (Low to High)","category":"Chest"},
  {"id":"CHEST_011","name":"Machine Chest Press","category":"Chest"},
  {"id":"CHEST_012","name":"Pec Deck Machine Fly","category":"Chest"},
  {"id":"CHEST_013","name":"Push-Up","category":"Chest"},
  {"id":"CHEST_014","name":"Decline Push-Up","category":"Chest"},
  {"id":"CHEST_015","name":"Diamond Push-Up","category":"Chest"},
  {"id":"CHEST_016","name":"Chest Dip","category":"Chest"},
  {"id":"CHEST_017","name":"Single-Arm Dumbbell Bench Press","category":"Chest"},
  {"id":"CHEST_018","name":"Landmine Press","category":"Chest"},
  {"id":"CHEST_019","name":"Single-Arm Cable Fly","category":"Chest"},
  {"id":"CHEST_020","name":"Dumbbell Pullover","category":"Chest"},
  {"id":"CHEST_021","name":"Smith Machine Bench Press","category":"Chest"},
  {"id":"CHEST_022","name":"Svend Press","category":"Chest"},
  {"id":"CHEST_023","name":"Resistance Band Push-Up","category":"Chest"},
  {"id":"CHEST_024","name":"Incline Machine Press","category":"Chest"},
  {"id":"CHEST_025","name":"Floor Press (Barbell)","category":"Chest"},
  {"id":"BACK_001","name":"Conventional Deadlift","category":"Back"},
  {"id":"BACK_002","name":"Barbell Bent-Over Row","category":"Back"},
  {"id":"BACK_003","name":"Single-Arm Dumbbell Row","category":"Back"},
  {"id":"BACK_004","name":"Pull-Up","category":"Back"},
  {"id":"BACK_005","name":"Chin-Up","category":"Back"},
  {"id":"BACK_006","name":"Lat Pulldown (Wide Grip)","category":"Back"},
  {"id":"BACK_007","name":"Lat Pulldown (Close Grip)","category":"Back"},
  {"id":"BACK_008","name":"Seated Cable Row","category":"Back"},
  {"id":"BACK_009","name":"T-Bar Row","category":"Back"},
  {"id":"BACK_010","name":"Pendlay Row","category":"Back"},
  {"id":"BACK_011","name":"Chest-Supported Dumbbell Row","category":"Back"},
  {"id":"BACK_012","name":"Cable Face Pull","category":"Back"},
  {"id":"BACK_013","name":"Meadows Row","category":"Back"},
  {"id":"BACK_014","name":"Inverted Row","category":"Back"},
  {"id":"BACK_015","name":"Straight-Arm Pulldown","category":"Back"},
  {"id":"BACK_016","name":"Machine Row (Plate-Loaded)","category":"Back"},
  {"id":"BACK_017","name":"Sumo Deadlift","category":"Back"},
  {"id":"BACK_018","name":"Rack Pull","category":"Back"},
  {"id":"BACK_019","name":"Kroc Row","category":"Back"},
  {"id":"BACK_020","name":"Seal Row","category":"Back"},
  {"id":"BACK_021","name":"Single-Arm Lat Pulldown","category":"Back"},
  {"id":"BACK_022","name":"Neutral-Grip Pull-Up","category":"Back"},
  {"id":"BACK_023","name":"Machine Lat Pulldown","category":"Back"},
  {"id":"BACK_024","name":"Resistance Band Pull-Apart","category":"Back"},
  {"id":"BACK_025","name":"Dumbbell Shrug Row","category":"Back"},
  {"id":"BACK_026","name":"Helms Row (Chest-Supported Machine Row)","category":"Back"},
  {"id":"BACK_027","name":"Single-Arm Cable Row","category":"Back"},
  {"id":"BACK_028","name":"Deficit Deadlift","category":"Back"},
  {"id":"BACK_029","name":"Snatch-Grip Deadlift","category":"Back"},
  {"id":"BACK_030","name":"Kayak Row (Alternating Cable Row)","category":"Back"},
  {"id":"SHOU_001","name":"Standing Barbell Overhead Press","category":"Shoulders"},
  {"id":"SHOU_002","name":"Seated Dumbbell Shoulder Press","category":"Shoulders"},
  {"id":"SHOU_003","name":"Arnold Press","category":"Shoulders"},
  {"id":"SHOU_004","name":"Dumbbell Lateral Raise","category":"Shoulders"},
  {"id":"SHOU_005","name":"Cable Lateral Raise","category":"Shoulders"},
  {"id":"SHOU_006","name":"Dumbbell Front Raise","category":"Shoulders"},
  {"id":"SHOU_007","name":"Rear Delt Fly (Dumbbell)","category":"Shoulders"},
  {"id":"SHOU_008","name":"Reverse Pec Deck","category":"Shoulders"},
  {"id":"SHOU_009","name":"Machine Shoulder Press","category":"Shoulders"},
  {"id":"SHOU_010","name":"Barbell Upright Row","category":"Shoulders"},
  {"id":"SHOU_011","name":"Single-Arm Dumbbell Overhead Press","category":"Shoulders"},
  {"id":"SHOU_012","name":"Behind-the-Neck Press","category":"Shoulders"},
  {"id":"SHOU_013","name":"Z Press","category":"Shoulders"},
  {"id":"SHOU_014","name":"Lu Raise","category":"Shoulders"},
  {"id":"SHOU_015","name":"Cable Front Raise","category":"Shoulders"},
  {"id":"SHOU_016","name":"Band Pull-Apart","category":"Shoulders"},
  {"id":"SHOU_017","name":"Handstand Push-Up","category":"Shoulders"},
  {"id":"SHOU_018","name":"Pike Push-Up","category":"Shoulders"},
  {"id":"SHOU_019","name":"Smith Machine Overhead Press","category":"Shoulders"},
  {"id":"SHOU_020","name":"Machine Lateral Raise","category":"Shoulders"},
  {"id":"SHOU_021","name":"Cable Rear Delt Fly","category":"Shoulders"},
  {"id":"SHOU_022","name":"Kettlebell Overhead Press","category":"Shoulders"},
  {"id":"SHOU_023","name":"Dumbbell Y-Raise","category":"Shoulders"},
  {"id":"SHOU_024","name":"Plate Front Raise","category":"Shoulders"},
  {"id":"SHOU_025","name":"Single-Arm Landmine Press","category":"Shoulders"},
  {"id":"TRAP_001","name":"Barbell Shrug","category":"Traps"},
  {"id":"TRAP_002","name":"Dumbbell Shrug","category":"Traps"},
  {"id":"TRAP_003","name":"Trap Bar Shrug","category":"Traps"},
  {"id":"TRAP_004","name":"Behind-the-Back Barbell Shrug","category":"Traps"},
  {"id":"TRAP_005","name":"Cable Shrug","category":"Traps"},
  {"id":"TRAP_006","name":"Farmer's Walk","category":"Traps"},
  {"id":"TRAP_007","name":"Overhead Shrug","category":"Traps"},
  {"id":"TRAP_008","name":"Single-Arm Dumbbell Shrug","category":"Traps"},
  {"id":"TRAP_009","name":"Prone Y-T-W Raise","category":"Traps"},
  {"id":"TRAP_010","name":"Machine Shrug","category":"Traps"},
  {"id":"BIC_001","name":"Standing Barbell Curl","category":"Biceps"},
  {"id":"BIC_002","name":"Standing Dumbbell Curl","category":"Biceps"},
  {"id":"BIC_003","name":"Incline Dumbbell Curl","category":"Biceps"},
  {"id":"BIC_004","name":"Preacher Curl (Barbell)","category":"Biceps"},
  {"id":"BIC_005","name":"Hammer Curl","category":"Biceps"},
  {"id":"BIC_006","name":"Concentration Curl","category":"Biceps"},
  {"id":"BIC_007","name":"Cable Bicep Curl","category":"Biceps"},
  {"id":"BIC_008","name":"EZ-Bar Curl","category":"Biceps"},
  {"id":"BIC_009","name":"Spider Curl","category":"Biceps"},
  {"id":"BIC_010","name":"Bayesian Cable Curl","category":"Biceps"},
  {"id":"BIC_011","name":"Machine Bicep Curl","category":"Biceps"},
  {"id":"BIC_012","name":"Single-Arm Preacher Curl (Dumbbell)","category":"Biceps"},
  {"id":"BIC_013","name":"Cross-Body Hammer Curl","category":"Biceps"},
  {"id":"BIC_014","name":"Zottman Curl","category":"Biceps"},
  {"id":"BIC_015","name":"EZ-Bar Preacher Curl","category":"Biceps"},
  {"id":"BIC_016","name":"Drag Curl","category":"Biceps"},
  {"id":"BIC_017","name":"Resistance Band Curl","category":"Biceps"},
  {"id":"BIC_018","name":"Kettlebell Curl","category":"Biceps"},
  {"id":"TRI_001","name":"Close-Grip Bench Press","category":"Triceps"},
  {"id":"TRI_002","name":"Tricep Rope Pushdown","category":"Triceps"},
  {"id":"TRI_003","name":"Overhead Tricep Extension (Dumbbell)","category":"Triceps"},
  {"id":"TRI_004","name":"Skull Crusher (EZ-Bar)","category":"Triceps"},
  {"id":"TRI_005","name":"Dip (Triceps Emphasis)","category":"Triceps"},
  {"id":"TRI_006","name":"Overhead Cable Tricep Extension","category":"Triceps"},
  {"id":"TRI_007","name":"Single-Arm Tricep Pushdown","category":"Triceps"},
  {"id":"TRI_008","name":"Kickback (Dumbbell)","category":"Triceps"},
  {"id":"TRI_009","name":"V-Bar Pushdown","category":"Triceps"},
  {"id":"TRI_010","name":"Bench Dip","category":"Triceps"},
  {"id":"TRI_011","name":"JM Press","category":"Triceps"},
  {"id":"TRI_012","name":"French Press (Barbell)","category":"Triceps"},
  {"id":"TRI_013","name":"Single-Arm Overhead Dumbbell Extension","category":"Triceps"},
  {"id":"TRI_014","name":"Machine Tricep Dip","category":"Triceps"},
  {"id":"TRI_015","name":"Tate Press","category":"Triceps"},
  {"id":"TRI_016","name":"Resistance Band Tricep Pushdown","category":"Triceps"},
  {"id":"TRI_017","name":"Cable Tricep Kickback","category":"Triceps"},
  {"id":"TRI_018","name":"Bodyweight Skull Crusher","category":"Triceps"},
  {"id":"FORE_001","name":"Barbell Wrist Curl","category":"Forearms"},
  {"id":"FORE_002","name":"Barbell Reverse Wrist Curl","category":"Forearms"},
  {"id":"FORE_003","name":"Dumbbell Wrist Curl","category":"Forearms"},
  {"id":"FORE_004","name":"Reverse Barbell Curl","category":"Forearms"},
  {"id":"FORE_005","name":"Plate Pinch Hold","category":"Forearms"},
  {"id":"FORE_006","name":"Dead Hang","category":"Forearms"},
  {"id":"FORE_007","name":"Fat Grip Dumbbell Hold","category":"Forearms"},
  {"id":"FORE_008","name":"Wrist Roller","category":"Forearms"},
  {"id":"NECK_001","name":"Neck Curl (Plate)","category":"Neck"},
  {"id":"NECK_002","name":"Neck Extension (Plate)","category":"Neck"},
  {"id":"NECK_003","name":"Neck Harness Extension","category":"Neck"},
  {"id":"NECK_004","name":"Band Neck Flexion","category":"Neck"},
  {"id":"NECK_005","name":"Band Neck Lateral Flexion","category":"Neck"},
  {"id":"ABS_001","name":"Crunch","category":"Abdominals"},
  {"id":"ABS_002","name":"Cable Crunch","category":"Abdominals"},
  {"id":"ABS_003","name":"Hanging Leg Raise","category":"Abdominals"},
  {"id":"ABS_004","name":"Hanging Knee Raise","category":"Abdominals"},
  {"id":"ABS_005","name":"Ab Wheel Rollout","category":"Abdominals"},
  {"id":"ABS_006","name":"Plank","category":"Abdominals"},
  {"id":"ABS_007","name":"Dead Bug","category":"Abdominals"},
  {"id":"ABS_008","name":"V-Up","category":"Abdominals"},
  {"id":"ABS_009","name":"Decline Sit-Up","category":"Abdominals"},
  {"id":"ABS_010","name":"Machine Crunch","category":"Abdominals"},
  {"id":"ABS_011","name":"Reverse Crunch","category":"Abdominals"},
  {"id":"ABS_012","name":"Toes-to-Bar","category":"Abdominals"},
  {"id":"ABS_013","name":"Hollow Body Hold","category":"Abdominals"},
  {"id":"ABS_014","name":"Dragon Flag","category":"Abdominals"},
  {"id":"ABS_015","name":"L-Sit","category":"Abdominals"},
  {"id":"ABS_016","name":"Bicycle Crunch","category":"Abdominals"},
  {"id":"ABS_017","name":"Lying Leg Raise","category":"Abdominals"},
  {"id":"ABS_018","name":"Cable Pallof Press","category":"Abdominals"},
  {"id":"ABS_019","name":"Weighted Crunch","category":"Abdominals"},
  {"id":"ABS_020","name":"GHD Sit-Up","category":"Abdominals"},
  {"id":"OBL_001","name":"Russian Twist","category":"Obliques"},
  {"id":"OBL_002","name":"Side Plank","category":"Obliques"},
  {"id":"OBL_003","name":"Cable Woodchop (High to Low)","category":"Obliques"},
  {"id":"OBL_004","name":"Cable Woodchop (Low to High)","category":"Obliques"},
  {"id":"OBL_005","name":"Hanging Oblique Knee Raise","category":"Obliques"},
  {"id":"OBL_006","name":"Dumbbell Side Bend","category":"Obliques"},
  {"id":"OBL_007","name":"Landmine Rotation","category":"Obliques"},
  {"id":"OBL_008","name":"Copenhagen Plank","category":"Obliques"},
  {"id":"OBL_009","name":"Suitcase Carry","category":"Obliques"},
  {"id":"OBL_010","name":"Medicine Ball Rotational Throw","category":"Obliques"},
  {"id":"LBCK_001","name":"Back Extension (45°)","category":"Lower Back"},
  {"id":"LBCK_002","name":"GHD Back Extension","category":"Lower Back"},
  {"id":"LBCK_003","name":"Superman","category":"Lower Back"},
  {"id":"LBCK_004","name":"Bird Dog","category":"Lower Back"},
  {"id":"LBCK_005","name":"Good Morning (Barbell)","category":"Lower Back"},
  {"id":"LBCK_006","name":"Reverse Hyperextension","category":"Lower Back"},
  {"id":"LBCK_007","name":"Cable Pull-Through","category":"Lower Back"},
  {"id":"LBCK_008","name":"Weighted Back Extension","category":"Lower Back"},
  {"id":"QUAD_001","name":"Barbell Back Squat","category":"Quadriceps"},
  {"id":"QUAD_002","name":"Barbell Front Squat","category":"Quadriceps"},
  {"id":"QUAD_003","name":"Goblet Squat","category":"Quadriceps"},
  {"id":"QUAD_004","name":"Leg Press","category":"Quadriceps"},
  {"id":"QUAD_005","name":"Hack Squat (Machine)","category":"Quadriceps"},
  {"id":"QUAD_006","name":"Leg Extension","category":"Quadriceps"},
  {"id":"QUAD_007","name":"Walking Lunge (Dumbbell)","category":"Quadriceps"},
  {"id":"QUAD_008","name":"Reverse Lunge (Barbell)","category":"Quadriceps"},
  {"id":"QUAD_009","name":"Bulgarian Split Squat","category":"Quadriceps"},
  {"id":"QUAD_010","name":"Step-Up (Dumbbell)","category":"Quadriceps"},
  {"id":"QUAD_011","name":"Smith Machine Squat","category":"Quadriceps"},
  {"id":"QUAD_012","name":"Sissy Squat","category":"Quadriceps"},
  {"id":"QUAD_013","name":"Single-Leg Leg Press","category":"Quadriceps"},
  {"id":"QUAD_014","name":"Single-Leg Extension","category":"Quadriceps"},
  {"id":"QUAD_015","name":"Pistol Squat","category":"Quadriceps"},
  {"id":"QUAD_016","name":"Trap Bar Squat","category":"Quadriceps"},
  {"id":"QUAD_017","name":"Bodyweight Squat","category":"Quadriceps"},
  {"id":"QUAD_018","name":"Dumbbell Split Squat","category":"Quadriceps"},
  {"id":"QUAD_019","name":"Pendulum Squat (Machine)","category":"Quadriceps"},
  {"id":"QUAD_020","name":"Belt Squat","category":"Quadriceps"},
  {"id":"QUAD_021","name":"Lateral Lunge (Dumbbell)","category":"Quadriceps"},
  {"id":"QUAD_022","name":"Wall Sit","category":"Quadriceps"},
  {"id":"QUAD_023","name":"Kettlebell Goblet Squat","category":"Quadriceps"},
  {"id":"QUAD_024","name":"Barbell Lunge","category":"Quadriceps"},
  {"id":"QUAD_025","name":"Spanish Squat","category":"Quadriceps"},
  {"id":"HAM_001","name":"Romanian Deadlift (Barbell)","category":"Hamstrings"},
  {"id":"HAM_002","name":"Romanian Deadlift (Dumbbell)","category":"Hamstrings"},
  {"id":"HAM_003","name":"Single-Leg Romanian Deadlift","category":"Hamstrings"},
  {"id":"HAM_004","name":"Lying Leg Curl","category":"Hamstrings"},
  {"id":"HAM_005","name":"Seated Leg Curl","category":"Hamstrings"},
  {"id":"HAM_006","name":"Nordic Hamstring Curl","category":"Hamstrings"},
  {"id":"HAM_007","name":"Stiff-Leg Deadlift","category":"Hamstrings"},
  {"id":"HAM_008","name":"Glute-Ham Raise","category":"Hamstrings"},
  {"id":"HAM_009","name":"Swiss Ball Leg Curl","category":"Hamstrings"},
  {"id":"HAM_010","name":"Kettlebell Swing (Russian)","category":"Hamstrings"},
  {"id":"HAM_011","name":"Single-Leg Lying Leg Curl","category":"Hamstrings"},
  {"id":"HAM_012","name":"Single-Leg Seated Leg Curl","category":"Hamstrings"},
  {"id":"HAM_013","name":"Cable Romanian Deadlift","category":"Hamstrings"},
  {"id":"HAM_014","name":"Band Leg Curl (Prone)","category":"Hamstrings"},
  {"id":"HAM_015","name":"Barbell Hip Hinge (Good Morning)","category":"Hamstrings"},
  {"id":"HAM_016","name":"Trap Bar Romanian Deadlift","category":"Hamstrings"},
  {"id":"HAM_017","name":"Sliding Leg Curl","category":"Hamstrings"},
  {"id":"HAM_018","name":"Kettlebell Single-Leg Deadlift","category":"Hamstrings"},
  {"id":"GLUT_001","name":"Barbell Hip Thrust","category":"Glutes"},
  {"id":"GLUT_002","name":"Glute Bridge (Bodyweight)","category":"Glutes"},
  {"id":"GLUT_003","name":"Single-Leg Glute Bridge","category":"Glutes"},
  {"id":"GLUT_004","name":"Single-Leg Hip Thrust","category":"Glutes"},
  {"id":"GLUT_005","name":"Cable Kickback","category":"Glutes"},
  {"id":"GLUT_006","name":"Machine Hip Thrust","category":"Glutes"},
  {"id":"GLUT_007","name":"Smith Machine Hip Thrust","category":"Glutes"},
  {"id":"GLUT_008","name":"Sumo Squat (Dumbbell)","category":"Glutes"},
  {"id":"GLUT_009","name":"Curtsy Lunge","category":"Glutes"},
  {"id":"GLUT_010","name":"Frog Pump","category":"Glutes"},
  {"id":"GLUT_011","name":"Donkey Kick","category":"Glutes"},
  {"id":"GLUT_012","name":"Fire Hydrant","category":"Glutes"},
  {"id":"GLUT_013","name":"Band-Resisted Clamshell","category":"Glutes"},
  {"id":"GLUT_014","name":"Banded Hip Thrust","category":"Glutes"},
  {"id":"GLUT_015","name":"Deficit Reverse Lunge","category":"Glutes"},
  {"id":"GLUT_016","name":"Cable Glute Pull-Through","category":"Glutes"},
  {"id":"GLUT_017","name":"Barbell Glute Bridge","category":"Glutes"},
  {"id":"GLUT_018","name":"Kickstand Romanian Deadlift","category":"Glutes"},
  {"id":"CALV_001","name":"Standing Calf Raise (Machine)","category":"Calves"},
  {"id":"CALV_002","name":"Seated Calf Raise","category":"Calves"},
  {"id":"CALV_003","name":"Single-Leg Calf Raise","category":"Calves"},
  {"id":"CALV_004","name":"Donkey Calf Raise","category":"Calves"},
  {"id":"CALV_005","name":"Smith Machine Calf Raise","category":"Calves"},
  {"id":"CALV_006","name":"Leg Press Calf Raise","category":"Calves"},
  {"id":"CALV_007","name":"Barbell Calf Raise","category":"Calves"},
  {"id":"CALV_008","name":"Tibialis Raise","category":"Calves"},
  {"id":"CALV_009","name":"Dumbbell Calf Raise","category":"Calves"},
  {"id":"CALV_010","name":"Bodyweight Calf Raise","category":"Calves"},
  {"id":"HADD_001","name":"Machine Hip Adduction","category":"Hip Adductors"},
  {"id":"HADD_002","name":"Cable Hip Adduction","category":"Hip Adductors"},
  {"id":"HADD_003","name":"Copenhagen Adductor Exercise","category":"Hip Adductors"},
  {"id":"HADD_004","name":"Sumo Squat","category":"Hip Adductors"},
  {"id":"HADD_005","name":"Wide-Stance Leg Press","category":"Hip Adductors"},
  {"id":"HADD_006","name":"Band-Resisted Adduction (Side-Lying)","category":"Hip Adductors"},
  {"id":"HABD_001","name":"Machine Hip Abduction","category":"Hip Abductors"},
  {"id":"HABD_002","name":"Cable Hip Abduction","category":"Hip Abductors"},
  {"id":"HABD_003","name":"Banded Lateral Walk","category":"Hip Abductors"},
  {"id":"HABD_004","name":"Side-Lying Hip Abduction","category":"Hip Abductors"},
  {"id":"HABD_005","name":"Standing Cable Hip Abduction","category":"Hip Abductors"},
  {"id":"HABD_006","name":"Banded Squat Walk","category":"Hip Abductors"},
  {"id":"FULL_001","name":"Barbell Clean and Press","category":"Full Body"},
  {"id":"FULL_002","name":"Thruster (Barbell)","category":"Full Body"},
  {"id":"FULL_003","name":"Dumbbell Thruster","category":"Full Body"},
  {"id":"FULL_004","name":"Burpee","category":"Full Body"},
  {"id":"FULL_005","name":"Turkish Get-Up","category":"Full Body"},
  {"id":"FULL_006","name":"Man Maker","category":"Full Body"},
  {"id":"FULL_007","name":"Devil Press","category":"Full Body"},
  {"id":"FULL_008","name":"Bear Crawl","category":"Full Body"},
  {"id":"FULL_009","name":"Kettlebell Clean","category":"Full Body"},
  {"id":"FULL_010","name":"Kettlebell Snatch","category":"Full Body"},
  {"id":"FULL_011","name":"Sandbag Clean and Press","category":"Full Body"},
  {"id":"FULL_012","name":"Dumbbell Clean and Press","category":"Full Body"},
  {"id":"FULL_013","name":"Wall Ball","category":"Full Body"},
  {"id":"FULL_014","name":"Sled Push","category":"Full Body"},
  {"id":"FULL_015","name":"Sled Pull (Hand-Over-Hand)","category":"Full Body"},
  {"id":"FULL_016","name":"Battle Rope Slam","category":"Full Body"},
  {"id":"FULL_017","name":"Rope Climb","category":"Full Body"},
  {"id":"FULL_018","name":"Trap Bar Deadlift","category":"Full Body"},
  {"id":"FULL_019","name":"Zercher Squat","category":"Full Body"},
  {"id":"FULL_020","name":"Kettlebell Complex (Clean + Press + Squat)","category":"Full Body"},
  {"id":"OLY_001","name":"Barbell Clean","category":"Olympic Lifts"},
  {"id":"OLY_002","name":"Barbell Snatch","category":"Olympic Lifts"},
  {"id":"OLY_003","name":"Power Clean","category":"Olympic Lifts"},
  {"id":"OLY_004","name":"Power Snatch","category":"Olympic Lifts"},
  {"id":"OLY_005","name":"Clean and Jerk","category":"Olympic Lifts"},
  {"id":"OLY_006","name":"Push Jerk","category":"Olympic Lifts"},
  {"id":"OLY_007","name":"Split Jerk","category":"Olympic Lifts"},
  {"id":"OLY_008","name":"Hang Clean","category":"Olympic Lifts"},
  {"id":"OLY_009","name":"Hang Snatch","category":"Olympic Lifts"},
  {"id":"OLY_010","name":"Clean Pull","category":"Olympic Lifts"},
  {"id":"OLY_011","name":"Snatch Pull","category":"Olympic Lifts"},
  {"id":"OLY_012","name":"Muscle Snatch","category":"Olympic Lifts"},
  {"id":"FUNC_001","name":"Kettlebell Swing (American)","category":"Functional Training"},
  {"id":"FUNC_002","name":"Kettlebell Goblet Carry","category":"Functional Training"},
  {"id":"FUNC_003","name":"Overhead Carry","category":"Functional Training"},
  {"id":"FUNC_004","name":"Sled Drag (Backward)","category":"Functional Training"},
  {"id":"FUNC_005","name":"Single-Arm Farmer's Walk","category":"Functional Training"},
  {"id":"FUNC_006","name":"Sandbag Bear Hug Carry","category":"Functional Training"},
  {"id":"FUNC_007","name":"Sandbag Shoulder","category":"Functional Training"},
  {"id":"FUNC_008","name":"Medicine Ball Slam","category":"Functional Training"},
  {"id":"FUNC_009","name":"Battle Rope Alternating Wave","category":"Functional Training"},
  {"id":"FUNC_010","name":"Tire Flip","category":"Functional Training"},
  {"id":"FUNC_011","name":"Waiter's Walk","category":"Functional Training"},
  {"id":"FUNC_012","name":"Atlas Stone Lift","category":"Functional Training"},
  {"id":"FUNC_013","name":"Yoke Walk","category":"Functional Training"},
  {"id":"FUNC_014","name":"Prowler Push","category":"Functional Training"},
  {"id":"FUNC_015","name":"Pallof Press Rotation","category":"Functional Training"},
  {"id":"FUNC_016","name":"Half-Kneeling Cable Chop","category":"Functional Training"},
  {"id":"FUNC_017","name":"Single-Arm Kettlebell Swing","category":"Functional Training"},
  {"id":"FUNC_018","name":"Crawling (Leopard Crawl)","category":"Functional Training"},
  {"id":"FUNC_019","name":"Bottoms-Up Kettlebell Press","category":"Functional Training"},
  {"id":"FUNC_020","name":"Steel Mace 360 Swing","category":"Functional Training"},
  {"id":"PLYO_001","name":"Box Jump","category":"Plyometrics"},
  {"id":"PLYO_002","name":"Depth Jump","category":"Plyometrics"},
  {"id":"PLYO_003","name":"Jump Squat","category":"Plyometrics"},
  {"id":"PLYO_004","name":"Split Squat Jump","category":"Plyometrics"},
  {"id":"PLYO_005","name":"Broad Jump","category":"Plyometrics"},
  {"id":"PLYO_006","name":"Tuck Jump","category":"Plyometrics"},
  {"id":"PLYO_007","name":"Plyo Push-Up","category":"Plyometrics"},
  {"id":"PLYO_008","name":"Medicine Ball Chest Pass","category":"Plyometrics"},
  {"id":"PLYO_009","name":"Lateral Bound","category":"Plyometrics"},
  {"id":"PLYO_010","name":"Single-Leg Box Jump","category":"Plyometrics"},
  {"id":"PLYO_011","name":"Hurdle Hop","category":"Plyometrics"},
  {"id":"PLYO_012","name":"Skater Jump","category":"Plyometrics"},
  {"id":"PLYO_013","name":"Altitude Drop","category":"Plyometrics"},
  {"id":"PLYO_014","name":"Weighted Box Jump","category":"Plyometrics"},
  {"id":"PLYO_015","name":"Star Jump","category":"Plyometrics"},
  {"id":"CARD_001","name":"Rowing Machine (Ergometer)","category":"Cardio & Conditioning"},
  {"id":"CARD_002","name":"Assault Bike","category":"Cardio & Conditioning"},
  {"id":"CARD_003","name":"Ski Ergometer","category":"Cardio & Conditioning"},
  {"id":"CARD_004","name":"Mountain Climber","category":"Cardio & Conditioning"},
  {"id":"CARD_005","name":"Jumping Jack","category":"Cardio & Conditioning"},
  {"id":"CARD_006","name":"High Knees","category":"Cardio & Conditioning"},
  {"id":"CARD_007","name":"Sprint Intervals","category":"Cardio & Conditioning"},
  {"id":"CARD_008","name":"Stair Climber Machine","category":"Cardio & Conditioning"},
  {"id":"CARD_009","name":"Elliptical Trainer","category":"Cardio & Conditioning"},
  {"id":"CARD_010","name":"Jump Rope (Skipping)","category":"Cardio & Conditioning"},
  {"id":"CARD_011","name":"Burpee Over Bar","category":"Cardio & Conditioning"},
  {"id":"CARD_012","name":"Kettlebell Carry Complex (Rack + Overhead)","category":"Cardio & Conditioning"},
  {"id":"CARD_013","name":"Shuttle Run","category":"Cardio & Conditioning"},
  {"id":"CARD_014","name":"Stationary Bike (Cycling)","category":"Cardio & Conditioning"},
  {"id":"CARD_015","name":"Treadmill Incline Walk","category":"Cardio & Conditioning"},
  {"id":"CHEST_026","name":"Dumbbell Squeeze Press","category":"Chest"},
  {"id":"CHEST_027","name":"Cable Chest Press","category":"Chest"},
  {"id":"CHEST_028","name":"Incline Smith Machine Press","category":"Chest"},
  {"id":"BACK_031","name":"Dumbbell Pullover (Back Emphasis)","category":"Back"},
  {"id":"BACK_032","name":"Barbell Row (Underhand Grip)","category":"Back"},
  {"id":"BACK_033","name":"Wide-Grip Seated Cable Row","category":"Back"},
  {"id":"BACK_034","name":"Machine Assisted Pull-Up","category":"Back"},
  {"id":"SHOU_026","name":"Dumbbell Upright Row","category":"Shoulders"},
  {"id":"SHOU_027","name":"Resistance Band Lateral Raise","category":"Shoulders"},
  {"id":"SHOU_028","name":"Seated Barbell Overhead Press","category":"Shoulders"},
  {"id":"BIC_019","name":"Cable Hammer Curl (Rope)","category":"Biceps"},
  {"id":"BIC_020","name":"Waiter Curl","category":"Biceps"},
  {"id":"BIC_021","name":"21s (Barbell Curl)","category":"Biceps"},
  {"id":"TRI_019","name":"Dumbbell Skull Crusher","category":"Triceps"},
  {"id":"TRI_020","name":"Cable Overhead Tricep Extension (Single-Arm)","category":"Triceps"},
  {"id":"FORE_009","name":"Behind-the-Back Barbell Wrist Curl","category":"Forearms"},
  {"id":"FORE_010","name":"Towel Hang","category":"Forearms"},
  {"id":"ABS_021","name":"Weighted Hanging Leg Raise","category":"Abdominals"},
  {"id":"ABS_022","name":"Decline Cable Crunch","category":"Abdominals"},
  {"id":"ABS_023","name":"Flutter Kicks","category":"Abdominals"},
  {"id":"OBL_011","name":"Cable Lateral Crunch","category":"Obliques"},
  {"id":"OBL_012","name":"Turkish Get-Up (Oblique Focus)","category":"Obliques"},
  {"id":"LBCK_009","name":"Barbell Hip Extension","category":"Lower Back"},
  {"id":"LBCK_010","name":"Prone Back Extension (Floor)","category":"Lower Back"},
  {"id":"QUAD_026","name":"Cyclist Squat","category":"Quadriceps"},
  {"id":"QUAD_027","name":"Landmine Goblet Squat","category":"Quadriceps"},
  {"id":"QUAD_028","name":"Reverse Lunge (Dumbbell)","category":"Quadriceps"},
  {"id":"HAM_019","name":"B-Stance Romanian Deadlift","category":"Hamstrings"},
  {"id":"HAM_020","name":"Cable Leg Curl (Standing)","category":"Hamstrings"},
  {"id":"GLUT_019","name":"Dumbbell Hip Thrust","category":"Glutes"},
  {"id":"GLUT_020","name":"Cable Romanian Deadlift (Glute Focus)","category":"Glutes"},
  {"id":"GLUT_021","name":"Banded Kickback","category":"Glutes"},
  {"id":"GLUT_022","name":"Machine Glute Kickback","category":"Glutes"},
  {"id":"CALV_011","name":"Single-Leg Seated Calf Raise","category":"Calves"},
  {"id":"CALV_012","name":"Jump Rope Calf Bounce","category":"Calves"},
  {"id":"HADD_007","name":"Goblet Squat (Wide Stance)","category":"Hip Adductors"},
  {"id":"HABD_007","name":"Standing Band Hip Abduction","category":"Hip Abductors"},
  {"id":"FULL_021","name":"Dumbbell Man Maker (Single-Arm)","category":"Full Body"},
  {"id":"FULL_022","name":"Barbell Complex (Deadlift + Row + Clean + Press + Squat)","category":"Full Body"},
  {"id":"FUNC_021","name":"Sandbag Over Shoulder","category":"Functional Training"},
  {"id":"FUNC_022","name":"Kettlebell Windmill","category":"Functional Training"},
  {"id":"FUNC_023","name":"Sandbag Carry (Bear Hug + Walk)","category":"Functional Training"},
  {"id":"FUNC_024","name":"Renegade Row","category":"Functional Training"},
  {"id":"FUNC_025","name":"Kettlebell Halo","category":"Functional Training"},
  {"id":"PLYO_016","name":"Pogos (Ankle Bounces)","category":"Plyometrics"},
  {"id":"PLYO_017","name":"Drop Push-Up","category":"Plyometrics"},
  {"id":"PLYO_018","name":"Lunge Jump (Alternating)","category":"Plyometrics"},
  {"id":"CARD_016","name":"Bike Sprints (Stationary)","category":"Cardio & Conditioning"},
  {"id":"CARD_017","name":"Rower Sprint Intervals","category":"Cardio & Conditioning"},
  {"id":"CARD_018","name":"Bear Crawl Sprint","category":"Cardio & Conditioning"},
  {"id":"TRAP_011","name":"Snatch-Grip High Pull","category":"Traps"},
  {"id":"TRAP_012","name":"Kettlebell Upright Row","category":"Traps"},
  {"id":"NECK_006","name":"4-Way Neck Machine","category":"Neck"},
  {"id":"CHEST_029","name":"Weighted Push-Up","category":"Chest"},
  {"id":"SHOU_029","name":"Dumbbell Scott Press","category":"Shoulders"},
  {"id":"BACK_035","name":"Meadows Chest-Supported Row","category":"Back"},
  {"id":"GLUT_023","name":"Hip Thrust (Feet-Elevated)","category":"Glutes"},
  {"id":"FUNC_026","name":"Single-Arm Suitcase Deadlift","category":"Functional Training"},
];
